import type { BankAccount, Contract, Counterparty, Invoice, User } from "../types";
import { uuid } from "./format";

function daysFromNow(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

// Демо-пользователь
const DEMO_USER_ID = "demo-user-001";

export const demoUser: User = {
  id: DEMO_USER_ID,
  email: "demo@vedtracker.com",
  passwordHash: "ef797c8188f6bcbf9fa0f5a400a1e1dbd1f6e4c5c7f5b8a0c7e3f8e5c7b8a0c7", // "demo123"
  name: "ООО «DemoCompany»",
  phone: "+7 999 123-45-67",
  address: "г. Москва, ул. Примерная, д. 1",
  inn: "7701234567",
  bankName: "ОАО «Альфа-банк»",
  bankAccount: "BY89ALFA30140000012340000000",
  bankSwift: "ALFABY2X",
  bankAddress: "г. Минск, ул. Сурганова, 43",
  createdAt: Date.now() - 365 * 86400000,
  lastLogin: Date.now(),
};

// ===== Демо-контрагенты =====
const cpId1 = uuid();
const cpId2 = uuid();
const cpId3 = uuid();
const cpId4 = uuid();
const cpId5 = uuid();

export const demoCounterparties: Counterparty[] = [
  {
    id: cpId1,
    userId: DEMO_USER_ID,
    name: "Globex GmbH",
    country: "Германия",
    address: "Berliner Str. 15, 10115 Berlin",
    taxId: "DE123456789",
    regNumber: "HRB 12345",
    contactPerson: "Hans Müller",
    phone: "+49 30 123456",
    email: "hans@globex.de",
    notes: "Постоянный клиент с 2023 года",
    createdAt: Date.now() - 180 * 86400000,
  },
  {
    id: cpId2,
    userId: DEMO_USER_ID,
    name: "Acme Trading Co.",
    country: "США",
    address: "123 Trade Blvd, New York, NY 10001",
    taxId: "US-EIN 12-3456789",
    regNumber: "",
    contactPerson: "John Smith",
    phone: "+1 212 555 0100",
    email: "john@acmetrading.com",
    notes: "",
    createdAt: Date.now() - 120 * 86400000,
  },
  {
    id: cpId3,
    userId: DEMO_USER_ID,
    name: "ООО «ЛесПромОпт»",
    country: "Россия",
    address: "г. Москва, ул. Промышленная, д. 42",
    taxId: "7701234567",
    regNumber: "1027700123456",
    contactPerson: "Сидоров А.П.",
    phone: "+7 495 123 45 67",
    email: "info@lespromopt.ru",
    notes: "Оплата в рублях, реквизиты подтверждены",
    createdAt: Date.now() - 90 * 86400000,
  },
  {
    id: cpId4,
    userId: DEMO_USER_ID,
    name: "ООО «Караван»",
    country: "Беларусь",
    address: "г. Минск, пр-т Независимости, 100",
    taxId: "100234567",
    regNumber: "190234567",
    contactPerson: "Иванов И.И.",
    phone: "+375 17 200 00 00",
    email: "karavan@mail.by",
    notes: "",
    createdAt: Date.now() - 60 * 86400000,
  },
  {
    id: cpId5,
    userId: DEMO_USER_ID,
    name: "Pacific Rim Ltd.",
    country: "Гонконг",
    address: "Unit 5, 10/F, Tower A, Kowloon",
    taxId: "HK-BR-9988776",
    regNumber: "CR-12345678",
    contactPerson: "Li Wei",
    phone: "+852 2345 6789",
    email: "li.wei@pacificrim.hk",
    notes: "Отменили последний заказ",
    createdAt: Date.now() - 200 * 86400000,
  },
];

// ===== Демо-договоры =====
const ctrId1 = uuid();
const ctrId2 = uuid();
const ctrId3 = uuid();
const ctrId4 = uuid();
const ctrId5 = uuid();
const ctrId6 = uuid();

export const demoContracts: Contract[] = [
  {
    id: ctrId1,
    userId: DEMO_USER_ID,
    contractNumber: "CTR-2025-GL1",
    date: daysFromNow(-365),
    expiryDate: daysFromNow(180),
    counterpartyId: cpId1,
    currency: "EUR",
    subject: "Поставка пиломатериалов хвойных пород",
    notes: "Основной рамочный контракт",
    createdAt: Date.now() - 365 * 86400000,
  },
  {
    id: ctrId6,
    userId: DEMO_USER_ID,
    contractNumber: "CTR-2026-GL2",
    date: daysFromNow(-10),
    expiryDate: daysFromNow(365),
    counterpartyId: cpId1,
    currency: "EUR",
    subject: "Поставка доски строганой (спецзаказ)",
    notes: "Дополнительное соглашение №2",
    createdAt: Date.now() - 10 * 86400000,
  },
  {
    id: ctrId2,
    userId: DEMO_USER_ID,
    contractNumber: "CTR-US-092",
    date: daysFromNow(-120),
    expiryDate: daysFromNow(240),
    counterpartyId: cpId2,
    currency: "USD",
    subject: "Экспорт изделий из древесины",
    notes: "",
    createdAt: Date.now() - 120 * 86400000,
  },
  {
    id: ctrId3,
    userId: DEMO_USER_ID,
    contractNumber: "№ ДГ-44/2025",
    date: daysFromNow(-90),
    expiryDate: daysFromNow(270),
    counterpartyId: cpId3,
    currency: "RUB",
    subject: "Поставка бруса строительного",
    notes: "Пролонгация автоматическая",
    createdAt: Date.now() - 90 * 86400000,
  },
  {
    id: ctrId4,
    userId: DEMO_USER_ID,
    contractNumber: "2026-BYN-04",
    date: daysFromNow(-60),
    expiryDate: daysFromNow(300),
    counterpartyId: cpId4,
    currency: "BYN",
    subject: "Оптовая отгрузка вагонки сосновой",
    notes: "",
    createdAt: Date.now() - 60 * 86400000,
  },
  {
    id: ctrId5,
    userId: DEMO_USER_ID,
    contractNumber: "CTR-HK-771",
    date: daysFromNow(-200),
    expiryDate: daysFromNow(-10),
    counterpartyId: cpId5,
    currency: "USD",
    subject: "Контракт на поставку опалубки",
    notes: "Срок истек",
    createdAt: Date.now() - 200 * 86400000,
  },
];

// ===== Демо-банковские счета =====
const baId1 = uuid();
const baId2 = uuid();
const baId3 = uuid();

export const demoBankAccounts: BankAccount[] = [
  {
    id: baId1,
    userId: DEMO_USER_ID,
    label: "Основной EUR",
    accountNumber: "BY89ALFA30140000012340000000",
    bankName: "ОАО «Альфа-банк»",
    bankCode: "ALFABY2X",
    bankAddress: "г. Минск, ул. Сурганова, 43",
    corrAccount: "",
    currency: "EUR",
    ownerName: "ООО «DemoCompany»",
    notes: "Для расчётов с ЕС",
    createdAt: Date.now() - 365 * 86400000,
  },
  {
    id: baId2,
    userId: DEMO_USER_ID,
    label: "USD счёт",
    accountNumber: "BY20PJCB30120000045670000000",
    bankName: "ОАО «Приорбанк»",
    bankCode: "PJCBBY2X",
    bankAddress: "г. Минск, ул. В. Хоружей, 31А",
    corrAccount: "3019914400001",
    currency: "USD",
    ownerName: "ООО «DemoCompany»",
    notes: "",
    createdAt: Date.now() - 365 * 86400000,
  },
  {
    id: baId3,
    userId: DEMO_USER_ID,
    label: "Рублёвый (RUB)",
    accountNumber: "RU40702810400000123456",
    bankName: "ОАО «Белинвестбанк»",
    bankCode: "BLBBBY2X",
    bankAddress: "г. Минск, ул. Мясникова, 14",
    corrAccount: "",
    currency: "RUB",
    ownerName: "ООО «DemoCompany»",
    notes: "Для клиентов из РФ",
    createdAt: Date.now() - 200 * 86400000,
  },
];

// ===== Демо-инвойсы =====
export const demoInvoices: Invoice[] = [
  {
    id: uuid(),
    userId: DEMO_USER_ID,
    invoiceNumber: "EXP-2026-001",
    clientName: "Globex GmbH",
    date: daysFromNow(-30),
    dueDate: daysFromNow(-5),
    amount: 12500,
    currency: "EUR",
    status: "paid",
    productName: "Пиломатериалы хвойные обрезные",
    additionalInfo: "Поставка в соответствии с договором CTR-2025-GL1. Товар соответствует ГОСТ 8486-86.",
    createdAt: Date.now() - 30 * 86400000,
    bankAccount: "BY89ALFA30140000012340000000",
    pricePerM3: 250,
    volumeM3: 50,
    incoterms: "FCA",
    grade: "1-3 сорт",
    size: "25x100x6000мм",
    counterpartyId: cpId1,
    bankAccountId: baId1,
    contractId: ctrId1,
    contractNumber: "CTR-2025-GL1",
  },
  {
    id: uuid(),
    userId: DEMO_USER_ID,
    invoiceNumber: "EXP-2026-002",
    clientName: "Acme Trading Co.",
    date: daysFromNow(-20),
    dueDate: daysFromNow(-2),
    amount: 8400,
    currency: "USD",
    status: "sent",
    productName: "Доска сухая строганая",
    additionalInfo: "Товар упакован в термоусадочную плёнку. Доставка DAP.",
    createdAt: Date.now() - 20 * 86400000,
    bankAccount: "BY20PJCB30120000045670000000",
    pricePerM3: 280,
    volumeM3: 30,
    incoterms: "DAP",
    grade: "Высший сорт (А)",
    size: "20x95x4000мм",
    counterpartyId: cpId2,
    bankAccountId: baId2,
    contractId: ctrId2,
    contractNumber: "CTR-US-092",
  },
  {
    id: uuid(),
    userId: DEMO_USER_ID,
    invoiceNumber: "EXP-2026-003",
    clientName: "ООО «ЛесПромОпт»",
    date: daysFromNow(-10),
    dueDate: daysFromNow(20),
    amount: 450000,
    currency: "RUB",
    status: "sent",
    productName: "Брус строительный непрофилированный",
    additionalInfo: "Поставка в рублях. Оплата по договору № ДГ-44/2025.",
    createdAt: Date.now() - 10 * 86400000,
    bankAccount: "RU40702810400000123456",
    pricePerM3: 15000,
    volumeM3: 30,
    incoterms: "FCA",
    grade: "2 сорт",
    size: "150x150x6000мм",
    counterpartyId: cpId3,
    bankAccountId: baId3,
    contractId: ctrId3,
    contractNumber: "№ ДГ-44/2025",
  },
  {
    id: uuid(),
    userId: DEMO_USER_ID,
    invoiceNumber: "EXP-2026-004",
    clientName: "ООО «Караван»",
    date: daysFromNow(-3),
    dueDate: daysFromNow(14),
    amount: 45000,
    currency: "BYN",
    status: "draft",
    productName: "Вагонка деревянная (сосна)",
    additionalInfo: "Черновик. Требуется согласование с клиентом.",
    createdAt: Date.now() - 3 * 86400000,
    bankAccount: "BY89ALFA30140000012340000000",
    pricePerM3: 750,
    volumeM3: 60,
    incoterms: "EXW",
    grade: "Сорт В",
    size: "12x96x3000мм",
    counterpartyId: cpId4,
    bankAccountId: baId1,
    contractId: ctrId4,
    contractNumber: "2026-BYN-04",
  },
  {
    id: uuid(),
    userId: DEMO_USER_ID,
    invoiceNumber: "EXP-2026-005",
    clientName: "Pacific Rim Ltd.",
    date: daysFromNow(-60),
    dueDate: daysFromNow(-40),
    amount: 5200,
    currency: "USD",
    status: "cancelled",
    productName: "Доска опалубочная",
    additionalInfo: "Контракт отменён покупателем.",
    createdAt: Date.now() - 60 * 86400000,
    bankAccount: "BY20PJCB30120000045670000000",
    pricePerM3: 130,
    volumeM3: 40,
    incoterms: "CIF",
    grade: "4 сорт",
    size: "22x150x6000мм",
    counterpartyId: cpId5,
    bankAccountId: baId2,
    contractId: ctrId5,
    contractNumber: "CTR-HK-771",
  },
];
